-- COMANDO SELECT RETORNANDO TODAS AS COLUNAS DA TABELA 

-- SELECT: O COMANDO PARA SELECIONAR OS DADOS
-- */NOME DA COLUNA: QUAIS SÃO AS COLUNAS QUE QUEREMOS RETORNAR
-- FROM: QUAL É A TABELA QUE DESEJA CONSULTAR?
SELECT * from pedido

-- LIMITANDO AS COLUNAS
SELECT id_pedido, metodo_pagamento from pedido

select * from produto
